services:
  trnode-tools:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trnode-tools
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:1234:1234"
